
Ext.define('Vega.model.Schedule', {
    extend:  'Vega.model.Base',

    fields:  [
        {name: 'POW', type: 'string'},
        {name: 'CUSTOMER'},
        {name: 'CXL', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'PAT', type: 'string'},
        {name: 'PCXL', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'NR', type: 'string'},
        {name: 'FABRICS'},
        {name: 'COLOR'},
        {name: 'STYLE'},
        {name: 'CUTNO'},
        {name: 'PDATE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'QTY', type: 'auto'},
        {name: 'CUTQTY', type: 'auto'},
        {name: 'CUT'},
        {name: 'CUTOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'CUTDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'CUTIN', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'SEWING'},
        {name: 'SEWOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'SEWDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'SEWIN', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'PRINTname'},
        {name: 'PRINT'},
        {name: 'PRTOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'PRTDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'PRTIN', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'STONE'},
        {name: 'STNOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'STNDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'STNIN', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'FINISH'},
        {name: 'FINOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'FINDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'FININ', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'TOPOUT', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'TOPDUE', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'TOPIN', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'CUSTPO'},
        {name: 'RouteDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'ETSDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'ShippedDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'FaMemo', type: 'string'},
        {name: 'OrderDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'DueDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'InDate', type: 'date', dateFormat: 'c', dateWriteFormat: 'Y-m-d'},
        {name: 'PaMemo'},
        {name: 'SODate', type: 'date', dateWriteFormat: 'Y-m-d'},
        {name: 'SRDate', type: 'date', dateWriteFormat: 'Y-m-d'},
        {name: 'STMemo', type: 'string'},
        {name: 'status'},
        {name: 'processtype'},
        {name: 'Field'}
    ],

    idProperty:  'CUTNO'
});
